site_name: 随身wifi教程
repo_name : codepy/portable-wifi
repo_url: https://github.com/codepy/portable-wifi
edit_uri : blob/main/docs/
theme:
  name: material
  palette:
    primary: 'teal'
    accent: 'teal'
  language: "zh"
  features:
    - content.action.edit
#    - content.action.view
nav:
  - 基础教程: index.md
  - 随身WiFi助手: 随身WIFI助手.md
  - debian教程: debian.md
  - 常见问题: 常见问题.md
  - 附件: 附件.md
  
markdown_extensions:
  - admonition