name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
<<<<<<< HEAD
      - run: pip install mkdocs-material mkdocs-glightbox
=======
      - run: pip install mkdocs-material mkdocs-glightbox      
>>>>>>> a17b6d36d3f2ddfa31b980069c2c7d4ef5c1f2f1
      - run: mkdocs gh-deploy --force
